# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
