# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='number',
            unique_together=set([('game', 'value')]),
        ),
    ]
